"""Initial migration

Revision ID: 489e21e7e61a
Revises:
Create Date: 2026-07-09 16:08:09.352059

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '489e21e7e61a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('api_key_hash', sa.String(), nullable=False))
    op.add_column('merchants', sa.Column('encrypted_session', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('webhook_secret', sa.String(), nullable=True))
    op.drop_index(op.f('ix_merchants_api_key'), table_name='merchants')
    op.create_index(op.f('ix_merchants_api_key_hash'), 'merchants', ['api_key_hash'], unique=True)
    op.drop_column('merchants', 'session_string')
    op.drop_column('merchants', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('api_key', sa.VARCHAR(), nullable=False))
    op.add_column('merchants', sa.Column('session_string', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_merchants_api_key_hash'), table_name='merchants')
    op.create_index(op.f('ix_merchants_api_key'), 'merchants', ['api_key'], unique=1)
    op.drop_column('merchants', 'webhook_secret')
    op.drop_column('merchants', 'encrypted_session')
    op.drop_column('merchants', 'api_key_hash')
    # ### end Alembic commands ###
