"""Add allowed_merchants table

Revision ID: ddd8903cdea2
Revises: 489e21e7e61a
Create Date: 2026-07-13 22:34:26.001619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddd8903cdea2"
down_revision: Union[str, Sequence[str], None] = "489e21e7e61a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowed_merchants",
        sa.Column("telegram_id", sa.String(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allowed_merchants")
    # ### end Alembic commands ###
