"""add receiving_card_mask

Revision ID: fb2b7b64b6c9
Revises: ddd8903cdea2
Create Date: 2026-07-13 23:53:43.797705

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb2b7b64b6c9"
down_revision: Union[str, Sequence[str], None] = "ddd8903cdea2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("receiving_card_mask", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "receiving_card_mask")
    # ### end Alembic commands ###
