name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Production Directory
        run: |
          rsync -avz --exclude '.env' --exclude 'venv' --exclude '__pycache__' --exclude 'scratch' --exclude '.git' ./ ~/AvtoPaymentBot/

      - name: Restart Docker Containers
        run: |
          cd ~/AvtoPaymentBot/backend
          echo 'master' | sudo -S docker-compose restart api worker
